spring:
  application:
    name: cyanea

  datasource:
    url: jdbc:h2:mem:cyaneadb
    username: cyanea
    password: 123
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      dll-auto: update

  h2:
    console.enabled: true
    console:
      path: /h2-console
      settings.trace: true
      settings.web-allow-others: true